services:

  gateway:
    build:
      context: ./gateway
      dockerfile: develope.Dockerfile
    user: root
    ports:
      - 8080:5000
    env_file:
      - .env
    environment:
      - rabbitDomainName=rabbit
    volumes:
      - ./gateway/src:/app/src
    depends_on:
      - rabbit

  users:
    build: ./users
    user: root
    env_file:
      - .env
    environment:
      - rabbitDomainName=rabbit
    volumes:
      - ./users/src:/app/src
    depends_on:
      - kafka

  trip:
    build: ./trip
    user: root
    env_file:
      - .env
    environment:
      - rabbitDomainName=rabbit
    volumes:
      - ./trip/src:/app/src
    depends_on:
      - rabbit
      - kafka

  # logger:
  #   build: ./logger
  #   user: root
  #   env_file:
  #     - .env
  #   environment:
  #     - rabbitDomainName=rabbit
  #   volumes:
  #     - ./logger/src:/app/src
  #   depends_on:
  #     - rabbit

  map_service:
    build: ./map_service
    user: root
    env_file:
      - .env
    environment:
      - rabbitDomainName=rabbit
    volumes:
      - ./map_service/src:/app/src

  rabbit:
    image: rabbitmq:3.10.5-management-alpine
    user: root
    ports:
      - 15672:15672

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
